# The default username is guacadmin with password guacadmin.
# 

version: '3.8'

services:
  guacd:
    container_name: ${APP_NAME}-guacd
    image: guacamole/guacd
    restart: always
    volumes:
      - drive:/drive:rw
      - record:/record:rw

  postgres:
    container_name: ${APP_NAME}-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data:rw

  guacamole:
    container_name: ${APP_NAME}
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    ports:
      - ${APP_PORT}:8080/tcp
      - 8080/tcp
    restart: always
    
volumes:
  postgres:
  record:
  drive:
  
networks:
  default:
      name: "${APP_NAME}"
